import {
  Wrench, Brain, SquareTerminal, Server, Layers,
  FlaskConical, Hammer, Package, Bug,
  Bot, BrainCircuit, MessageSquare,
  DatabaseZap, Cloud,
  Terminal, Library, Plug, Puzzle,
  Palette, Component, ServerCog, Gamepad2,
  GraduationCap, Star,
  Table2, Send, FolderOpen,
  ShieldCheck, FolderTree,
  Rocket, ScrollText,
  Bell,
  Binary, Hexagon, Blocks,
  WandSparkles,
  Shapes, Braces, Sparkle, Plug2, LayoutTemplate,
  Atom, ClipboardList,
  Waypoints, PenTool, Variable,
  Container, Router, Stamp,
  Languages, SlidersHorizontal, FolderGit2,
  Clapperboard, ScanText,
  Type, FileCog,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { IconType } from 'react-icons'
import {
  PiCodeBlockFill,
  PiTerminalWindowFill,
  PiNotebookFill,
  PiTextColumnsFill,
  PiColumnsFill,
  PiCodeSimpleFill,
  PiFunctionFill,
  PiSpeedometerFill,
  PiArticleFill,
  PiDeviceMobileFill,
  PiAppWindowFill,
  PiChartPieFill,
  PiLockFill,
  PiBrainFill,
  PiDatabaseFill,
  PiRobotFill,
  PiFactoryFill,
  PiEyeFill,
  PiBookOpenFill,
  PiChalkboardTeacherFill,
  PiGraduationCapFill,
  PiBriefcaseFill,
  PiTrophyFill,
  PiArrowsLeftRightFill,
  PiPlayFill,
  PiSealCheckFill,
  PiLightbulbFilamentFill,
  PiPackageFill,
  PiInfinityFill,
  PiHeartbeatFill,
  PiNetworkFill,
  PiQueueFill,
  PiMagnifyingGlassFill,
  PiBroomFill,
  PiKeyFill,
  PiGlobeSimpleFill,
  PiGearFill,
  PiFileArrowDownFill,
} from 'react-icons/pi'
import { RiTerminalBoxFill } from 'react-icons/ri'
import { FaSpider } from 'react-icons/fa6'

export type AnyIcon = LucideIcon | IconType

export const BUCKET_ICONS: Record<string, AnyIcon> = {
  'dev-tools':      Wrench,
  'frameworks':     Shapes,
  'ai-ml':          Brain,
  'learning':       GraduationCap,
  'editors':        SquareTerminal,
  'lang-projects':  Binary,
  'infrastructure': Server,
  'utilities':      Layers,
}

export const SUB_TYPE_ICONS: Record<string, AnyIcon> = {
  // Dev Tools
  'algorithm':       PiFunctionFill,
  'testing':         FlaskConical,
  'build-tool':      Hammer,
  'pkg-manager':     Package,
  'linter':          PiBroomFill,
  'formatter':       Braces,
  'debugger':        Bug,
  'vcs-tool':        FolderGit2,
  'profiler':        PiSpeedometerFill,
  'code-generator':  Sparkle,
  'doc-tool':        PiArticleFill,
  'static-analysis': ShieldCheck,
  'api-tool':        Plug2,
  'monorepo-tool':   FolderTree,
  // Frameworks
  'web-framework':     LayoutTemplate,
  'css-framework':     Palette,
  'ui-library':        Component,
  'backend-framework': ServerCog,
  'mobile-framework':  PiDeviceMobileFill,
  'game-engine':       Gamepad2,
  'desktop-framework': PiAppWindowFill,
  'state-management':  Atom,
  'data-viz':          PiChartPieFill,
  'animation':         Clapperboard,
  'auth-library':      PiLockFill,
  // AI & ML
  'ai-model':        Bot,
  'ml-framework':    PiBrainFill,
  'dataset':         PiDatabaseFill,
  'neural-net':      BrainCircuit,
  'ai-agent':        PiRobotFill,
  'prompt-lib':      MessageSquare,
  'mlops':           PiFactoryFill,
  'computer-vision': PiEyeFill,
  'nlp-tool':        ScanText,
  'vector-db':       Hexagon,
  'ai-coding':       WandSparkles,
  // Learning
  'book':             PiBookOpenFill,
  'tutorial':         PiChalkboardTeacherFill,
  'awesome-list':     Star,
  'course':           PiGraduationCapFill,
  'cheatsheet':       ClipboardList,
  'interview-prep':   PiBriefcaseFill,
  'roadmap':          Waypoints,
  'coding-challenge': PiTrophyFill,
  'research-paper':   PiArticleFill,
  // Editors & IDEs
  'code-editor':    PiCodeSimpleFill,
  'ide':            PiCodeBlockFill,
  'terminal':       PiTerminalWindowFill,
  'notebook':       PiNotebookFill,
  'text-editor':    PiTextColumnsFill,
  'design-tool':    PenTool,
  'db-client':      Table2,
  'api-client-app': Send,
  'diff-tool':      PiColumnsFill,
  'file-manager':   FolderOpen,
  // Language Projects
  'lang-impl':    Variable,
  'style-guide':  Type,
  'transpiler':   PiArrowsLeftRightFill,
  'runtime':      PiPlayFill,
  'compiler':     FileCog,
  'type-checker': PiSealCheckFill,
  'lang-server':  PiLightbulbFilamentFill,
  'repl':         RiTerminalBoxFill,
  'pkg-registry': PiPackageFill,
  // Infrastructure
  'database':       DatabaseZap,
  'container':      Container,
  'devops':         PiInfinityFill,
  'cloud-platform': Cloud,
  'monitoring':     PiHeartbeatFill,
  'networking':     PiNetworkFill,
  'message-queue':  PiQueueFill,
  'blockchain':     Blocks,
  'ci-cd':          Rocket,
  'search-engine':  PiMagnifyingGlassFill,
  'auth-infra':     PiKeyFill,
  'api-gateway':    Router,
  'logging':        ScrollText,
  // Utilities
  'cli-tool':        Terminal,
  'library':         Library,
  'platform':        PiGlobeSimpleFill,
  'api-client':      Plug,
  'boilerplate':     Stamp,
  'plugin':          Puzzle,
  'automation':      PiGearFill,
  'scraper':         FaSpider,
  'file-converter':  PiFileArrowDownFill,
  'i18n':            Languages,
  'config-tool':     SlidersHorizontal,
  'notification':    Bell,
}
