export type RepoSubType = { id: string; label: string; bucket: string }
export type RepoBucket  = { id: string; label: string; color: string; subTypes: RepoSubType[] }

export const REPO_BUCKETS: RepoBucket[] = [
  {
    id: 'dev-tools', label: 'Dev Tools', color: '#3b82f6',
    subTypes: [
      { id: 'algorithm',  label: 'Algorithm',    bucket: 'dev-tools' },
      { id: 'testing',    label: 'Testing',       bucket: 'dev-tools' },
      { id: 'build-tool', label: 'Build Tool',    bucket: 'dev-tools' },
      { id: 'pkg-manager',label: 'Pkg Manager',   bucket: 'dev-tools' },
      { id: 'linter',     label: 'Linter',        bucket: 'dev-tools' },
      { id: 'formatter',  label: 'Formatter',     bucket: 'dev-tools' },
      { id: 'debugger',   label: 'Debugger',      bucket: 'dev-tools' },
      { id: 'vcs-tool',   label: 'VCS Tool',      bucket: 'dev-tools' },
      { id: 'profiler',       label: 'Profiler',        bucket: 'dev-tools' },
      { id: 'code-generator', label: 'Code Generator',  bucket: 'dev-tools' },
      { id: 'doc-tool',       label: 'Documentation Tool', bucket: 'dev-tools' },
      { id: 'static-analysis',label: 'Static Analysis', bucket: 'dev-tools' },
      { id: 'api-tool',       label: 'API Tool',        bucket: 'dev-tools' },
      { id: 'monorepo-tool',  label: 'Monorepo Tool',   bucket: 'dev-tools' },
    ],
  },
  {
    id: 'frameworks', label: 'Frameworks', color: '#10b981',
    subTypes: [
      { id: 'web-framework',     label: 'Web Framework',     bucket: 'frameworks' },
      { id: 'css-framework',     label: 'CSS Framework',     bucket: 'frameworks' },
      { id: 'ui-library',        label: 'UI Library',        bucket: 'frameworks' },
      { id: 'backend-framework', label: 'Backend Framework', bucket: 'frameworks' },
      { id: 'mobile-framework',  label: 'Mobile Framework',  bucket: 'frameworks' },
      { id: 'game-engine',       label: 'Game Engine',       bucket: 'frameworks' },
      { id: 'desktop-framework', label: 'Desktop Framework', bucket: 'frameworks' },
      { id: 'state-management',  label: 'State Management',  bucket: 'frameworks' },
      { id: 'data-viz',          label: 'Data Viz',          bucket: 'frameworks' },
      { id: 'animation',         label: 'Animation',         bucket: 'frameworks' },
      { id: 'auth-library',      label: 'Auth Library',      bucket: 'frameworks' },
    ],
  },
  {
    id: 'ai-ml', label: 'AI & ML', color: '#8b5cf6',
    subTypes: [
      { id: 'ai-model',    label: 'AI Model',      bucket: 'ai-ml' },
      { id: 'ml-framework',label: 'ML Framework',  bucket: 'ai-ml' },
      { id: 'dataset',     label: 'Dataset',       bucket: 'ai-ml' },
      { id: 'neural-net',  label: 'Neural Net',    bucket: 'ai-ml' },
      { id: 'ai-agent',    label: 'AI Agent',      bucket: 'ai-ml' },
      { id: 'prompt-lib',  label: 'Prompt Lib',    bucket: 'ai-ml' },
      { id: 'mlops',           label: 'MLOps',           bucket: 'ai-ml' },
      { id: 'computer-vision', label: 'Computer Vision', bucket: 'ai-ml' },
      { id: 'nlp-tool',        label: 'NLP Tool',        bucket: 'ai-ml' },
      { id: 'vector-db',       label: 'Vector DB',       bucket: 'ai-ml' },
      { id: 'ai-coding',       label: 'AI Coding',       bucket: 'ai-ml' },
    ],
  },
  {
    id: 'learning', label: 'Learning', color: '#f97316',
    subTypes: [
      { id: 'book',         label: 'Book',          bucket: 'learning' },
      { id: 'tutorial',     label: 'Tutorial',      bucket: 'learning' },
      { id: 'awesome-list', label: 'Awesome List',  bucket: 'learning' },
      { id: 'course',       label: 'Course',        bucket: 'learning' },
      { id: 'cheatsheet',   label: 'Cheatsheet',    bucket: 'learning' },
      { id: 'interview-prep',  label: 'Interview Prep',  bucket: 'learning' },
      { id: 'roadmap',         label: 'Roadmap',         bucket: 'learning' },
      { id: 'coding-challenge',label: 'Coding Challenge', bucket: 'learning' },
      { id: 'research-paper',  label: 'Research Paper',  bucket: 'learning' },
    ],
  },
  {
    id: 'editors', label: 'Editors & IDEs', color: '#14b8a6',
    subTypes: [
      { id: 'code-editor', label: 'Code Editor',   bucket: 'editors' },
      { id: 'ide',         label: 'IDE',            bucket: 'editors' },
      { id: 'terminal',    label: 'Terminal',       bucket: 'editors' },
      { id: 'notebook',    label: 'Notebook',       bucket: 'editors' },
      { id: 'text-editor', label: 'Text Editor',    bucket: 'editors' },
      { id: 'design-tool', label: 'Design Tool',    bucket: 'editors' },
      { id: 'db-client',       label: 'Database Client', bucket: 'editors' },
      { id: 'api-client-app',  label: 'REST Client',     bucket: 'editors' },
      { id: 'diff-tool',       label: 'Diff Tool',       bucket: 'editors' },
      { id: 'file-manager',    label: 'File Manager',    bucket: 'editors' },
    ],
  },
  {
    id: 'lang-projects', label: 'Language Projects', color: '#ec4899',
    subTypes: [
      { id: 'lang-impl',   label: 'Language Impl',  bucket: 'lang-projects' },
      { id: 'style-guide', label: 'Style Guide',    bucket: 'lang-projects' },
      { id: 'transpiler',  label: 'Transpiler',     bucket: 'lang-projects' },
      { id: 'runtime',     label: 'Runtime',        bucket: 'lang-projects' },
      { id: 'compiler',    label: 'Compiler',       bucket: 'lang-projects' },
      { id: 'type-checker', label: 'Type Checker',      bucket: 'lang-projects' },
      { id: 'lang-server',  label: 'Language Server',    bucket: 'lang-projects' },
      { id: 'repl',         label: 'REPL',              bucket: 'lang-projects' },
      { id: 'pkg-registry', label: 'Package Registry',  bucket: 'lang-projects' },
    ],
  },
  {
    id: 'infrastructure', label: 'Infrastructure', color: '#ef4444',
    subTypes: [
      { id: 'database',      label: 'Database',       bucket: 'infrastructure' },
      { id: 'container',     label: 'Container',      bucket: 'infrastructure' },
      { id: 'devops',        label: 'DevOps',         bucket: 'infrastructure' },
      { id: 'cloud-platform',label: 'Cloud Platform', bucket: 'infrastructure' },
      { id: 'monitoring',    label: 'Monitoring',     bucket: 'infrastructure' },
      { id: 'networking',    label: 'Networking',     bucket: 'infrastructure' },
      { id: 'blockchain',    label: 'Blockchain',     bucket: 'infrastructure' },
      { id: 'message-queue', label: 'Message Queue',  bucket: 'infrastructure' },
      { id: 'ci-cd',         label: 'CI/CD',          bucket: 'infrastructure' },
      { id: 'search-engine', label: 'Search Engine',  bucket: 'infrastructure' },
      { id: 'auth-infra',    label: 'Auth / Identity', bucket: 'infrastructure' },
      { id: 'api-gateway',   label: 'API Gateway',    bucket: 'infrastructure' },
      { id: 'logging',       label: 'Logging',        bucket: 'infrastructure' },
    ],
  },
  {
    id: 'utilities', label: 'Utilities', color: '#64748b',
    subTypes: [
      { id: 'cli-tool',    label: 'CLI Tool',    bucket: 'utilities' },
      { id: 'library',     label: 'Library',     bucket: 'utilities' },
      { id: 'platform',    label: 'Platform',    bucket: 'utilities' },
      { id: 'api-client',  label: 'API Client',  bucket: 'utilities' },
      { id: 'boilerplate', label: 'Boilerplate', bucket: 'utilities' },
      { id: 'plugin',      label: 'Plugin',      bucket: 'utilities' },
      { id: 'automation',  label: 'Automation',  bucket: 'utilities' },
      { id: 'scraper',        label: 'Scraper',        bucket: 'utilities' },
      { id: 'file-converter', label: 'File Converter',  bucket: 'utilities' },
      { id: 'i18n',           label: 'i18n',            bucket: 'utilities' },
      { id: 'config-tool',    label: 'Config Tool',     bucket: 'utilities' },
      { id: 'notification',   label: 'Notification',    bucket: 'utilities' },
    ],
  },
]

export const REPO_SUB_TYPES: RepoSubType[] =
  REPO_BUCKETS.flatMap(b => b.subTypes)
